# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mirror Glass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mirror Glass
  pod 'Alamofire', '~> 5.6.1'
  pod 'AlamofireImage', '~> 4.2.0'
  pod 'PureLayout', '~> 3.1.9'
  pod 'R.swift', '~> 6.1.0'
  pod 'SVProgressHUD', '~> 2.2.5'
  
  # ReactiveX
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxSwiftExt', '~> 6.0.1'
  pod 'NSObject+Rx', '~> 5.2.2'

  target 'Mirror GlassTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble', '~> 10.0.0'
    pod 'Quick', '~> 5.0.1'
  end
end

